stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim
    - src/features/feature_engineering.py
    outs:
    - data/processed
    - models/scaler.pkl
  model_preparation:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:
    - model_building.hyperparameters.n_estimators
    - model_building.hyperparameters.max_depth
    - model_building.hyperparameters.min_samples_split
    - model_building.hyperparameters.min_samples_leaf
    - model_building.cv
    - model_building.n_iter
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json
    outs:
    - reports/experiment_info.json
  register_model:
    cmd: python src/model/register_model.py
    deps:
    - reports/experiment_info.json
    - src/model/register_model.py
  
