data_ingestion:
  test_size: 0.18

model_building:
  hyperparameters:
    n_estimators: [50, 100, 150, 200]
    max_depth: [null, 10, 20, 30, 40, 50]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
  cv: 3 
  n_iter: 20